---
- name: Set internal DNS name
  set_fact: 
    internal_name: "ip-{{ hostvars[inventory_hostname].ansible_default_ipv4.address|replace('.', '-') }}.{{ hostvars[inventory_hostname].ansible_dns.search[0]}}"

- name: Get my public IP
  community.general.ipify_facts:
    timeout: 60

- name: Apply known_hosts template
  template:
    src: known_hosts.j2
    dest: /etc/ssh/ssh_known_hosts

- name: Enable HostbasedUsesNameFromPacketOnly on sshd_config
  lineinfile: 
    path: /etc/ssh/sshd_config
    regexp: 'HostbasedUsesNameFromPacketOnly.*'
    line: "HostbasedUsesNameFromPacketOnly yes"
    state: present

- name: Enable SSH Key Sign on /etc/ssh/ssh_config
  lineinfile:
    dest: /etc/ssh/ssh_config
    regexp: 'EnableSSHKeysign.*'
    line: "EnableSSHKeysign yes"

- name: Verify SSH config
  command: sshd -t
  changed_when: false

- name: Restart SSH server
  service:
    name: ssh
    state: restarted
  ignore_errors: True
  register: ssh_restart

- name: Restart SSH server using command
  command: service ssh restart
  when: ssh_restart.failed is true

